const ADVERTISERS = 'advertisers';
const CAMPAIGNS = 'campaigns';
const CREATIVES = 'creatives';
const FLIGHTS = 'flights';

/**
 * Contains the key to identify the User in a {@link DecisionResponse}
 * <p>
 * The response contains the key used to identify the unique user that places the request. All user keys
 * are generated by the API. You can target to a user when you place a {@link Request}.
 *
 * Not supported:
 * - pendingConversions, partnerUserIds, retargettingSegments, cookieMonster, dirtyCookies
 */
export interface User {
    key: string;
    isNew?: boolean;
    interests?: string[];
    customProperties?: any;
    optOut?: boolean;
    blockedItems?: Map<string, number[]>;
    flightViewTimes?: Map<number, number[]>;
    adViewTimes?: Map<number, number[]>;
    siteViewTimes?: Map<number, number[]>;
}
